### ISSUE TITLE
When I try the example, i get the following error: Precondition Failed

### ISSUE THREAD

**Issue by rolfberkenbosch** [bachya/pytile#15]
**Describe the bug**
Today i bought 2 tile sticker. I was able the activate them in the app. Then i try to get the information with this python module. But I get an error message: Precondition Failed.

**To Reproduce**
I go to the pypi page of pytile. And use the example (Create a client, initialize it, and get to work)
Then i fill in the correct login credentials. When i run python3 test.py I get that message.

**Expected behavior**
I should work.

**Screenshots**

```
[pytile]$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "test.py", line 15, in main
    await client.tiles.all()
  File "/usr/local/lib/python3.7/site-packages/pytile/tile.py", line 31, in all
    "get", "tiles", params=[("tile_uuids", uuid) for uuid in tile_uuid_list]
  File "/usr/local/lib/python3.7/site-packages/pytile/client.py", line 105, in request
    ) from None
pytile.errors.RequestError: Error requesting data from tiles: 412, message='Precondition Failed', url=URL('https://production.tile-api.com/api/v1/tiles?tile_uuids=********&tile_uuids=p!*******&tile_uuids=p!******')
```

**Comment by bachya** [comment]
What are the contents of `test.py`? That's not a file in this repo.

**Comment by rolfberkenbosch** [comment]
This is my content:

import asyncio

from aiohttp import ClientSession

from pytile import Client


async def main() -> None:
    """Create the aiohttp session and run the example."""
    async with ClientSession() as websession:
        client = Client("rolf@berkenbosch.nl", "********", websession)
        await client.async_init()

        # Get all Tiles associated with an account:
        await client.tiles.all()


asyncio.get_event_loop().run_until_complete(main())

**Comment by bachya** [comment]
That looks good.

When I run the exact same code with my credentials, my Tile data comes back as expected (no `412` error). 

I'm curious about the first line of your description:

>Today i bought 2 tile sticker.

Are you referring to [these](https://www.thetileapp.com/en-us/store/tiles/sticker)? If so, that's a possible difference (since I don't have that kind of tracker). Let me know and we can debug from there.

**Comment by rolfberkenbosch** [comment]
Yes, indeed. What I can do is reset my password and send my account to you so that you can test it.

**Comment by bachya** [comment]
That would be amazing; I'll treat it confidentially and let you know as soon as I'm done. You can reach me at bachya1208@gmail.com.

**Comment by rolfberkenbosch** [comment]
I have send you an email.

**Comment by bachya** [comment]
Got it! I can reproduce the error; will follow up when I have more info.

**Comment by rolfberkenbosch** [comment]
Good to hear!

**Comment by bachya** [comment]
@rolfberkenbosch Can you pull the latest `dev` and see if your script works?

**Comment by rolfberkenbosch** [comment]
@bachya there is an error in your new example:

`
import asyncio

from aiohttp import ClientSession

from pytile import login

async def main() -> None:
    """Create the aiohttp session and run the example."""
    async with ClientSession() as websession:
        client = await login("rolf@berkenbosch.nl", "*******", websession)

        # Get all Tiles associated with an account:
        await client.tiles.all()


asyncio.get_event_loop().run_until_complete(main())
`

`
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from pytile import login
ImportError: cannot import name 'login' from 'pytile' (/Users/rolfberkenbosch/Projects/Git/pytile/pytile/__init__.py)
`

**Comment by rolfberkenbosch** [comment]
Instead of login, we should use async_login

**Comment by rolfberkenbosch** [comment]
With pypi package 3.0.0 i'm not getting any errors. So you have fixed it ? Because your example let not see any output of locations of the trackers.

**Comment by rolfberkenbosch** [comment]
@bachya I can confirm it is working. I have modified the files in home-assistant, and it is also working with the pypi 3.0.0 version.  Should I send  the fix to home-assistant ?

**Comment by bachya** [comment]
>@bachya there is an error in your new example:

Good catch; I'll get that fixed.

>@bachya I can confirm it is working. I have modified the files in home-assistant, and it is also working with the pypi 3.0.0 version. Should I send the fix to home-assistant ?

Wonderful! If you have the time and inclination to submit a HASS PR, please do.
